[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Vincent Moeykens",email = "vincent@moeykens.net"},
]
dependencies = []
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

